# Generated by Django 4.1.5 on 2023-01-18 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='아이디어 설명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_user', to='posts.tool', verbose_name='예상 개발툴'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/%Y%m%d', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='아이디어 관심도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, verbose_name='아이디어명'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='content',
            field=models.TextField(verbose_name='개발툴 설명'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='kind',
            field=models.CharField(max_length=30, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
    ]
