# Generated by Django 4.1.5 on 2023-01-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_likes_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
    ]
