# Generated by Django 4.1.5 on 2023-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='local',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
