# Generated by Django 4.1.5 on 2023-01-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_already_like_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='already_like',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
